### ISSUE TITLE
Using in authoring tool

### ISSUE THREAD

**Issue by derhuebiii** [deltanet/adapt-contrib-narrative-audio#28]
Hi,

I installed the plugin and also the audio extension - no errors all good. I have added a narrative and also mp3s, but I cannot get any audio control.

What am I missing?

Thanks!
Kind regards,
Tim

**Comment by RobertPeek** [comment]
Hi Tim

It's hard to say without seeing perhaps the exported JSON from the Authoring Tool.

The main audio extension will need to be enabled in the Project settings. Then for it to work on the Narrative Audio component the audio needs to be added and enabled at component level:

![image](https://user-images.githubusercontent.com/7251995/46524189-e567ff80-c87f-11e8-873e-3bd8ab067967.png)

The Narrative audio will only work if it is enabled on the component like above so my guess is it isn't. Once enabled on the component the audio added to each item will play.

Hope that helps.

Rob

**Comment by derhuebiii** [comment]
Hi Rob,

Thanks! The screenshot helped - I was already wondering if the general audio component doesn't have any options.

The solution to my problem was, that I installed the wrong one. It needed to be this one:
https://github.com/deltanet/adapt-audio

and NOT
https://github.com/cgkineo/adapt-audio

Kind regards,
Tim
