### ISSUE TITLE
Having no component body text can cause layout issues when used with other plugins

### ISSUE THREAD

**Issue by deltanetdan** [deltanet/adapt-contrib-narrative-audio#38]
If used with the icon-popup extension and no component body text is added the narrative item text layout is disturbed.
![narrative-issue-image](https://user-images.githubusercontent.com/4161219/180818243-16312086-8c6b-45ee-ab17-27f437dabeb9.png)

Caused by conflict in CSS with item body text and icon-popup both having float: right.

Adding the following CSS solves the issue:

```
.narrativeaudio__widget {
    clear: both;
}
```

**Comment by deltanetdan** [comment]
Even with the clear: both added the icon popup bitton is overlaying the audio button. Perhaps icon-popup needs changing so it does not use float right. 

Question: as this is really icon popup causing the issue should this be fixed in that extension?

**Comment by deltanetdan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Narrative audio layout issue](https://trello.com/c/MLtLu9v2/186-narrative-audio-layout-issue)

**Comment by RobertPeek** [comment]
Fixed in: https://github.com/deltanet/adapt-icon-popup/issues/53
