### ISSUE TITLE
Layout and arrows not correct  RTL on iPhone

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-contrib-narrative-audio#4]
![img_2284](https://cloud.githubusercontent.com/assets/6452430/17474051/e26598f2-5d4b-11e6-9ca2-4b522ad626ea.PNG)

and 

![img_2285](https://cloud.githubusercontent.com/assets/6452430/17474063/f74a8854-5d4b-11e6-815a-7b253f57e23c.PNG)

**Comment by RobertPeek** [comment]
Fixed in #7
